// Exported
export default {
    id: 34,
    name: 'Dual Xtec EQ1',
    category: 'Equalizer',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Low boost',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Low frequency',
            type: 'select',
            options: [
                { id: 0, name: '20 Hz' },
                { id: 1, name: '30 Hz' },
                { id: 2, name: '60 Hz' },
                { id: 3, name: '100 Hz' },
            ],
        },
        {
            id: 4,
            number: '05',
            name: 'A | Low attenuation',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'A | High bandwidth',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'A | High boost',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'A | High frequency',
            type: 'select',
            options: [
                { id: 0, name: '3 kHz' },
                { id: 1, name: '4 kHz' },
                { id: 2, name: '5 kHz' },
                { id: 3, name: '8 kHz' },
                { id: 4, name: '10 kHz' },
                { id: 5, name: '12 kHz' },
                { id: 6, name: '16 kHz' },
            ],
        },
        {
            id: 8,
            number: '09',
            name: 'A | High attenuation',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'A | Attenuation selector',
            type: 'select',
            options: [
                { id: 0, name: '5 kHz' },
                { id: 1, name: '10 kHz' },
                { id: 2, name: '20 kHz' },
            ],
        },
        {
            id: 10,
            number: '11',
            name: 'A | Transfer',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 11,
            number: '12',
            name: 'B | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 12,
            number: '13',
            name: 'B | Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 13,
            number: '14',
            name: 'B | Low boost',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 14,
            number: '15',
            name: 'B | Low frequency',
            type: 'select',
            options: [
                { id: 0, name: '20 Hz' },
                { id: 1, name: '30 Hz' },
                { id: 2, name: '60 Hz' },
                { id: 3, name: '100 Hz' },
            ],
        },
        {
            id: 15,
            number: '16',
            name: 'B | Low attenuation',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 16,
            number: '17',
            name: 'B | High bandwidth',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 17,
            number: '18',
            name: 'B | High boost',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 18,
            number: '19',
            name: 'B | High frequency',
            type: 'select',
            options: [
                { id: 0, name: '3 kHz' },
                { id: 1, name: '4 kHz' },
                { id: 2, name: '5 kHz' },
                { id: 3, name: '8 kHz' },
                { id: 4, name: '10 kHz' },
                { id: 5, name: '12 kHz' },
                { id: 6, name: '16 kHz' },
            ],
        },
        {
            id: 19,
            number: '20',
            name: 'B | High attenuation',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 20,
            number: '21',
            name: 'B | Attenuation selector',
            type: 'select',
            options: [
                { id: 0, name: '5 kHz' },
                { id: 1, name: '10 kHz' },
                { id: 2, name: '20 kHz' },
            ],
        },
        {
            id: 21,
            number: '22',
            name: 'B | Transfer',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
