// Exported
export default {
    id: 31,
    name: 'Dual DeEsser',
    category: 'De esser',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | Low band reduction',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'A | High band reduction',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '05',
            name: 'A | Male',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 3,
            number: '03',
            name: 'B | Low band reduction',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '04',
            name: 'B | High band reduction',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'B | Male',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
