// Exported
export default {
    id: 40,
    name: 'Dual Combinator',
    category: 'Other',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | Bypass',
            type: 'boolean',
            style: 'offOn',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Band',
            type: 'select',
            options: [
                { id: 0, name: 'All' },
                { id: 1, name: 'Low' },
                { id: 2, name: 'Low mid' },
                { id: 3, name: 'Mid' },
                { id: 4, name: 'High mid' },
                { id: 5, name: 'High' },
            ],
        },
        {
            id: 2,
            number: '03',
            name: 'A | Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Attack',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 19,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'A | Release',
            type: 'double',
            precision: 0,
            minimum: 20,
            maximum: 3000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'A | Auto',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 6,
            number: '07',
            name: 'A | Speed SBC',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'A | SBC',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 8,
            number: '09',
            name: 'A | X-Over',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'A | 48v',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 10,
            number: '11',
            name: 'A | X-Over',
            type: 'select',
            options: [
                { id: 0, name: '1.1' },
                { id: 1, name: '1.2' },
                { id: 2, name: '1.3' },
                { id: 3, name: '1.5' },
                { id: 4, name: '1.7' },
                { id: 5, name: '2' },
                { id: 6, name: '2.5' },
                { id: 7, name: '3' },
                { id: 8, name: '3.5' },
                { id: 9, name: '4' },
                { id: 10, name: '5' },
                { id: 11, name: '7' },
                { id: 12, name: '10' },
                { id: 13, name: 'Limit' },
            ],
        },
        {
            id: 11,
            number: '12',
            name: 'A | Trim threshold',
            type: 'double',
            precision: 1,
            minimum: -40,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 12,
            number: '13',
            name: 'A | Trim gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 13,
            number: '14',
            name: 'A | Low band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 14,
            number: '15',
            name: 'A | Low band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 15,
            number: '16',
            name: 'A | Low band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 16,
            number: '17',
            name: 'A | Low mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 17,
            number: '18',
            name: 'A | Low mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 18,
            number: '19',
            name: 'A | Low mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 19,
            number: '20',
            name: 'A | Mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 20,
            number: '21',
            name: 'A | Mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 21,
            number: '22',
            name: 'A | Mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 22,
            number: '23',
            name: 'A | High mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 23,
            number: '24',
            name: 'A | High mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 24,
            number: '25',
            name: 'A | High mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 25,
            number: '26',
            name: 'A | High band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 26,
            number: '27',
            name: 'A | High band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 27,
            number: '28',
            name: 'A | High band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 28,
            number: '29',
            name: 'A | Meters',
            type: 'select',
            options: [
                { id: 0, name: 'Band gain reduction' },
                { id: 1, name: 'Band level meters (peak)' },
                { id: 2, name: 'Automatic spectrum balance' },
            ],
        },
        {
            id: 29,
            number: '30',
            name: 'B | Bypass',
            type: 'boolean',
            style: 'offOn',
        },
        {
            id: 30,
            number: '31',
            name: 'B | Band',
            type: 'select',
            options: [
                { id: 0, name: 'All' },
                { id: 1, name: 'Low' },
                { id: 2, name: 'Low mid' },
                { id: 3, name: 'Mid' },
                { id: 4, name: 'High mid' },
                { id: 5, name: 'High' },
            ],
        },
        {
            id: 31,
            number: '32',
            name: 'B | Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 32,
            number: '33',
            name: 'B | Attack',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 19,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 33,
            number: '34',
            name: 'B | Release',
            type: 'double',
            precision: 0,
            minimum: 20,
            maximum: 3000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 34,
            number: '35',
            name: 'B | Auto',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 35,
            number: '36',
            name: 'B | Speed SBC',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 36,
            number: '37',
            name: 'B | SBC',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 37,
            number: '38',
            name: 'B | X-Over',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 38,
            number: '39',
            name: 'B | 48v',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 39,
            number: '40',
            name: 'B | X-Over',
            type: 'select',
            options: [
                { id: 0, name: '1.1' },
                { id: 1, name: '1.2' },
                { id: 2, name: '1.3' },
                { id: 3, name: '1.5' },
                { id: 4, name: '1.7' },
                { id: 5, name: '2' },
                { id: 6, name: '2.5' },
                { id: 7, name: '3' },
                { id: 8, name: '3.5' },
                { id: 9, name: '4' },
                { id: 10, name: '5' },
                { id: 11, name: '7' },
                { id: 12, name: '10' },
                { id: 13, name: 'Limit' },
            ],
        },
        {
            id: 40,
            number: '41',
            name: 'B | Trim threshold',
            type: 'double',
            precision: 1,
            minimum: -40,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 41,
            number: '42',
            name: 'B | Trim gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 42,
            number: '43',
            name: 'B | Low band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 43,
            number: '44',
            name: 'B | Low band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 44,
            number: '45',
            name: 'B | Low band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 45,
            number: '46',
            name: 'B | Low mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 46,
            number: '47',
            name: 'B | Low mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 47,
            number: '48',
            name: 'B | Low mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 48,
            number: '49',
            name: 'B | Mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 49,
            number: '50',
            name: 'B | Mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 50,
            number: '51',
            name: 'B | Mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 51,
            number: '52',
            name: 'B | High mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 52,
            number: '53',
            name: 'B | High mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 53,
            number: '54',
            name: 'B | High mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 54,
            number: '55',
            name: 'B | High band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 55,
            number: '56',
            name: 'B | High band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 56,
            number: '57',
            name: 'B | High band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 57,
            number: '58',
            name: 'B | Meters',
            type: 'select',
            options: [
                { id: 0, name: 'Band gain reduction' },
                { id: 1, name: 'Band level meters (peak)' },
                { id: 2, name: 'Automatic spectrum balance' },
            ],
        },
    ],
};
