// Exported
export default {
    id: 14,
    name: 'Stereo Flanger',
    category: 'Modulation',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Speed',
            type: 'double',
            style: 'tap',
            precision: 2,
            minimum: 0.05,
            maximum: 5,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Width L',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Width R',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Delay L',
            type: 'double',
            precision: 1,
            minimum: 0.5,
            maximum: 20,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Delay R',
            type: 'double',
            precision: 1,
            minimum: 0.5,
            maximum: 20,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 6,
            number: '07',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'High cut',
            type: 'double',
            precision: 0,
            minimum: 200,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Phase',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 180,
            unit: '°',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'Feed low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'Feedback high cut',
            type: 'double',
            precision: 0,
            minimum: 200,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'Feed',
            type: 'double',
            precision: 0,
            minimum: -90,
            maximum: 90,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
