// Exported
export default {
    id: 28,
    name: 'Stereo Graphic EQ',
    category: 'Equalizer',
    parameters: [
        {
            id: 0,
            number: '01',
            name: '20',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: '25',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: '31.5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: '40',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: '50',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: '63',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: '80',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: '100',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: '125',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: '160',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: '200',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: '250',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 12,
            number: '13',
            name: '315',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 13,
            number: '14',
            name: '400',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 14,
            number: '15',
            name: '500',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 15,
            number: '16',
            name: '630',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 16,
            number: '17',
            name: '800',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 17,
            number: '18',
            name: '1k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 18,
            number: '19',
            name: '1k25',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 19,
            number: '20',
            name: '1k6',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 20,
            number: '21',
            name: '2k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 21,
            number: '22',
            name: '2k5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 22,
            number: '23',
            name: '3k15',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 23,
            number: '24',
            name: '4k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 24,
            number: '25',
            name: '5k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 25,
            number: '26',
            name: '6k3',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 26,
            number: '27',
            name: '8k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 27,
            number: '28',
            name: '10k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 28,
            number: '29',
            name: '12k5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 29,
            number: '30',
            name: '16k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 30,
            number: '31',
            name: '20k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 31,
            number: '32',
            name: 'Master',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
