// Exported
export default {
    id: 18,
    name: 'Rotary Speaker',
    category: 'Modulation',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Low speed',
            type: 'double',
            style: 'tap',
            precision: 2,
            minimum: 0.1,
            maximum: 4,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'High speed',
            type: 'double',
            style: 'tap',
            precision: 2,
            minimum: 2,
            maximum: 10,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Acceleration',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Distance',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Balance',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 5,
            number: '06',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 6,
            number: '07',
            name: 'Stop',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 7,
            number: '08',
            name: 'Low / High speed rotate',
            type: 'boolean',
            style: 'toggle',
        },
    ],
};
