// Exported
export default {
    id: 35,
    name: 'Stereo Xtec EQ5',
    category: 'Equalizer',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Low frequency',
            type: 'select',
            options: [
                { id: 0, name: '200 Hz' },
                { id: 1, name: '300 Hz' },
                { id: 2, name: '500 Hz' },
                { id: 3, name: '700 Hz' },
                { id: 4, name: '1 kHz' },
            ],
        },
        {
            id: 3,
            number: '04',
            name: 'Low boost',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Mid frequency',
            type: 'select',
            options: [
                { id: 0, name: '200 Hz' },
                { id: 1, name: '300 Hz' },
                { id: 2, name: '500 Hz' },
                { id: 3, name: '700 Hz' },
                { id: 4, name: '1 kHz' },
                { id: 5, name: '1.5 kHz' },
                { id: 6, name: '2 kHz' },
                { id: 7, name: '3 kHz' },
                { id: 8, name: '4 kHz' },
                { id: 9, name: '5 kHz' },
                { id: 10, name: '7 kHz' },
            ],
        },
        {
            id: 5,
            number: '06',
            name: 'Mid cut',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'High frequency',
            type: 'select',
            options: [
                { id: 0, name: '1.5 kHz' },
                { id: 1, name: '2 kHz' },
                { id: 2, name: '3 kHz' },
                { id: 3, name: '4 kHz' },
                { id: 4, name: '5 kHz' },
            ],
        },
        {
            id: 7,
            number: '08',
            name: 'High boost',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Transfer',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
