// Exported
export default {
    id: 46,
    name: 'Stereo Ultimo Compressor',
    category: 'Compressor',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'Input',
            type: 'double',
            precision: 0,
            minimum: -48,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Output',
            type: 'double',
            precision: 0,
            minimum: -48,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Attack',
            type: 'double',
            precision: 1,
            minimum: 1,
            maximum: 7,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Release',
            type: 'double',
            precision: 1,
            minimum: 1,
            maximum: 7,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Ratio',
            type: 'select',
            options: [
                { id: 0, name: '4' },
                { id: 1, name: '8' },
                { id: 2, name: '12' },
                { id: 3, name: '20' },
                { id: 4, name: 'Limit' },
            ],
        },
    ],
};
