// Exported
export default {
    id: 53,
    name: 'Edison EX1',
    category: 'Other',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'M/S input',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 2,
            number: '03',
            name: 'M/S Output',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 3,
            number: '04',
            name: 'Stereo spread',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'LMF spread',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Balance',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Center distance',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'Output gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
