// Exported
export default {
    id: 6,
    name: 'Vintage Reverb',
    category: 'Reverb',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Pre delay',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 120,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Decay',
            type: 'double',
            precision: 2,
            minimum: 0.4,
            maximum: 4.5,
            unit: 's',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Modulation',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Vintage',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 4,
            number: '05',
            name: 'Front / rear',
            type: 'boolean',
            style: 'toggle',
        },
        {
            id: 5,
            number: '06',
            name: 'Level',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'High cut',
            type: 'double',
            precision: 0,
            minimum: 10000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Low multiplier',
            type: 'double',
            precision: 2,
            minimum: 0.5,
            maximum: 2,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'High multiplier',
            type: 'double',
            precision: 2,
            minimum: 0.25,
            maximum: 1,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
