// Exported
export default {
    id: 33,
    name: 'Stereo Xtec EQ1',
    category: 'Equalizer',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Low boost',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Low frequency',
            type: 'select',
            options: [
                { id: 0, name: '20 Hz' },
                { id: 1, name: '30 Hz' },
                { id: 2, name: '60 Hz' },
                { id: 3, name: '100 Hz' },
            ],
        },
        {
            id: 4,
            number: '05',
            name: 'Low attenuation',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'High bandwidth',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'High boost',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'High frequency',
            type: 'select',
            options: [
                { id: 0, name: '3 kHz' },
                { id: 1, name: '4 kHz' },
                { id: 2, name: '5 kHz' },
                { id: 3, name: '8 kHz' },
                { id: 4, name: '10 kHz' },
                { id: 5, name: '12 kHz' },
                { id: 6, name: '16 kHz' },
            ],
        },
        {
            id: 8,
            number: '09',
            name: 'High attenuation',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'Attenuation selector',
            type: 'select',
            options: [
                { id: 0, name: '5 kHz' },
                { id: 1, name: '10 kHz' },
                { id: 2, name: '20 kHz' },
            ],
        },
        {
            id: 10,
            number: '11',
            name: 'Transfer',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
