// Exported
export default {
    id: 21,
    name: 'Delay + Chamber',
    category: 'Reverb',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Time',
            type: 'double',
            style: 'tap',
            precision: 0,
            minimum: 1,
            maximum: 3000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Pattern',
            type: 'select',
            options: [
                { id: 0, name: '1/4' },
                { id: 1, name: '1/3' },
                { id: 2, name: '3/8' },
                { id: 3, name: '1/2' },
                { id: 4, name: '2/3' },
                { id: 5, name: '3/4' },
                { id: 6, name: '1' },
                { id: 7, name: '1/4X' },
                { id: 8, name: '1/3X' },
                { id: 9, name: '3/8X' },
                { id: 10, name: '1/2X' },
                { id: 11, name: '2/3X' },
                { id: 12, name: '3/4X' },
                { id: 13, name: '1X' },
            ],
        },
        {
            id: 2,
            number: '03',
            name: 'Feed low cut',
            type: 'double',
            precision: 0,
            minimum: 1000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Feedback',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'XFeed',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Balance',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 6,
            number: '07',
            name: 'Pre delay',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 200,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'Decay',
            type: 'double',
            precision: 2,
            minimum: 0.1,
            maximum: 5,
            unit: 's',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Size',
            type: 'double',
            precision: 0,
            minimum: 2,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'Damp',
            type: 'double',
            precision: 0,
            minimum: 1000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
    ],
};
