// Exported
export default {
    id: 26,
    name: 'Modulation Delay',
    category: 'Delay',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Time',
            type: 'double',
            style: 'tap',
            precision: 0,
            minimum: 1,
            maximum: 3000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Pattern',
            type: 'select',
            options: [
                { id: 0, name: 'Delay' },
                { id: 1, name: '1/2' },
                { id: 2, name: '2/3' },
                { id: 3, name: '3/2' },
            ],
        },
        {
            id: 2,
            number: '03',
            name: 'Feedback',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'High cut',
            type: 'double',
            precision: 0,
            minimum: 200,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Depth',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Rate',
            type: 'double',
            precision: 2,
            minimum: 0.05,
            maximum: 10,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'Ser',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 8,
            number: '09',
            name: 'Type',
            type: 'select',
            options: [
                { id: 0, name: 'Ambience' },
                { id: 1, name: 'Club' },
                { id: 2, name: 'Hall' },
            ],
        },
        {
            id: 9,
            number: '10',
            name: 'Decay',
            type: 'double',
            precision: 1,
            minimum: 1,
            maximum: 10,
            unit: 's',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'High damp',
            type: 'double',
            precision: 0,
            minimum: 1000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'Balance',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 12,
            number: '13',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
    ],
};
