// Exported
export default {
    id: 19,
    name: 'Tremolo / Panner',
    category: 'Modulation',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Speed',
            type: 'double',
            style: 'tap',
            precision: 2,
            minimum: 0.05,
            maximum: 5,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Phase',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 180,
            unit: '°',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Wave',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Depth',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Env speed',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Env depth',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Attack',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 1000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'Hold',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 2000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Release',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 1000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
