// Exported
export default {
    id: 59,
    name: 'Dual Pitch Shifter',
    category: 'Pitch',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | Semi',
            type: 'double',
            precision: 0,
            minimum: -12,
            maximum: 12,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Cent',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Delay',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 500,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Gain',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'A | Pan',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 5,
            number: '06',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 6,
            number: '07',
            name: 'B | Semi',
            type: 'double',
            precision: 0,
            minimum: -12,
            maximum: 12,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'B | Cent',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'B | Delay',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 500,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'B | Gain',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'B | Pan',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 11,
            number: '12',
            name: 'High cut',
            type: 'double',
            precision: 0,
            minimum: 2000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
    ],
};
