// Exported
export default {
    id: 15,
    name: 'Stereo Phaser',
    category: 'Modulation',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Speed',
            type: 'double',
            style: 'tap',
            precision: 2,
            minimum: 0.05,
            maximum: 5,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Depth',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Resonance',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 80,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Base',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Stages',
            type: 'double',
            precision: 0,
            minimum: 2,
            maximum: 12,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 6,
            number: '07',
            name: 'Wave',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'Phase',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 180,
            unit: '°',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Env mod',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 9,
            number: '10',
            name: 'Attack',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 1000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'Hold',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 2000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'Release',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 1000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
