// Exported
export default {
    id: 37,
    name: 'Wave Designer',
    category: 'Enhancer',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | Attack',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Sustain',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Gain',
            type: 'double',
            precision: 1,
            minimum: -24,
            maximum: 24,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'B | Attack',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 4,
            number: '05',
            name: 'B | Sustain',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 5,
            number: '06',
            name: 'B | Gain',
            type: 'double',
            precision: 1,
            minimum: -24,
            maximum: 24,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
