// Exported
export default {
    id: 45,
    name: 'Dual Leisure Compressor',
    category: 'Compressor',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Gain',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Peak reduction',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Compressor / limiter',
            type: 'boolean',
            style: 'toggle',
        },
        {
            id: 4,
            number: '05',
            name: 'A | Output gain',
            type: 'double',
            precision: 0,
            minimum: -18,
            maximum: 6,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'B | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 6,
            number: '07',
            name: 'B | Gain',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'B | Peak reduction',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'B | Compressor / limiter',
            type: 'boolean',
            style: 'toggle',
        },
        {
            id: 9,
            number: '10',
            name: 'B | Output gain',
            type: 'double',
            precision: 0,
            minimum: -18,
            maximum: 6,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
