// Exported
export default {
    id: 55,
    name: 'Dual Guitar Amp',
    category: 'Amp simulation',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | Preamp',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Buzz',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Punch',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Crunch',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'A | Drive',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'A | Level',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'A | Low',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'A | High',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'A | Cabinet',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 9,
            number: '10',
            name: 'B | Preamp',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'B | Buzz',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'B | Punch',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 12,
            number: '13',
            name: 'B | Crunch',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 13,
            number: '14',
            name: 'B | Drive',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 14,
            number: '15',
            name: 'B | Level',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 15,
            number: '16',
            name: 'B | Low',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 16,
            number: '17',
            name: 'B | High',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 17,
            number: '18',
            name: 'B | Cabinet',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
