// Exported
export default {
    id: 43,
    name: 'Dual Fair Compressor',
    category: 'Compressor',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Gain',
            type: 'double',
            precision: 1,
            minimum: -20,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Threshold',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Time',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 6,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'A | Bias',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'A | Output gain',
            type: 'double',
            precision: 0,
            minimum: -18,
            maximum: 6,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'A | Balance',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 7,
            number: '08',
            name: 'A | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 8,
            number: '09',
            name: 'B | Gain',
            type: 'double',
            precision: 1,
            minimum: -20,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'B | Threshold',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'B | Time',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 6,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'B | Bias',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 12,
            number: '13',
            name: 'B | Output gain',
            type: 'double',
            precision: 0,
            minimum: -18,
            maximum: 6,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 13,
            number: '14',
            name: 'B | Balance',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
    ],
};
