// Exported
export default {
    id: 17,
    name: 'Mood Filter',
    category: 'Modulation',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Speed',
            type: 'double',
            style: 'tap',
            precision: 2,
            minimum: 0.05,
            maximum: 20,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Depth',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Resonance',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Base',
            type: 'double',
            precision: 0,
            minimum: 20,
            maximum: 15000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Mode',
            type: 'select',
            options: [
                { id: 0, name: 'LP' },
                { id: 1, name: 'HP' },
                { id: 2, name: 'BP' },
                { id: 3, name: 'Notch' },
            ],
        },
        {
            id: 5,
            number: '06',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 6,
            number: '07',
            name: 'Wave',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 6,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'Phase',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 180,
            unit: '°',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Env mod',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 9,
            number: '10',
            name: 'Attack',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 250,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'Release',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'Drive',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 12,
            number: '13',
            name: 'Poles',
            type: 'select',
            options: [
                { id: 0, name: '2' },
                { id: 1, name: '4' },
            ],
        },
        {
            id: 13,
            number: '14',
            name: 'Sidechain',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
