// Exported
export default {
    id: 60,
    name: 'Stereo Pitch Shifter',
    category: 'Pitch',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Semi',
            type: 'double',
            precision: 0,
            minimum: -12,
            maximum: 12,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Cent',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Delay',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 500,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'High cut',
            type: 'double',
            precision: 0,
            minimum: 2000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
    ],
};
