// Exported
export default {
    id: 39,
    name: 'Stereo Combinator',
    category: 'Other',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Bypass',
            type: 'boolean',
            style: 'offOn',
        },
        {
            id: 1,
            number: '02',
            name: 'Band',
            type: 'select',
            options: [
                { id: 0, name: 'All' },
                { id: 1, name: 'Low' },
                { id: 2, name: 'Low mid' },
                { id: 3, name: 'Mid' },
                { id: 4, name: 'High mid' },
                { id: 5, name: 'High' },
            ],
        },
        {
            id: 2,
            number: '03',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 3,
            number: '04',
            name: 'Attack',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 19,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Release',
            type: 'double',
            precision: 0,
            minimum: 20,
            maximum: 3000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Auto',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 6,
            number: '07',
            name: 'Speed SBC',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'SBC',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 8,
            number: '09',
            name: 'X-Over',
            type: 'double',
            precision: 0,
            minimum: -50,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: '48v',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 10,
            number: '11',
            name: 'X-Over',
            type: 'select',
            options: [
                { id: 0, name: '1.1' },
                { id: 1, name: '1.2' },
                { id: 2, name: '1.3' },
                { id: 3, name: '1.5' },
                { id: 4, name: '1.7' },
                { id: 5, name: '2' },
                { id: 6, name: '2.5' },
                { id: 7, name: '3' },
                { id: 8, name: '3.5' },
                { id: 9, name: '4' },
                { id: 10, name: '5' },
                { id: 11, name: '7' },
                { id: 12, name: '10' },
                { id: 13, name: 'Limit' },
            ],
        },
        {
            id: 11,
            number: '12',
            name: 'Trim threshold',
            type: 'double',
            precision: 1,
            minimum: -40,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 12,
            number: '13',
            name: 'Trim gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 13,
            number: '14',
            name: 'Low band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 14,
            number: '15',
            name: 'Low band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 15,
            number: '16',
            name: 'Low band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 16,
            number: '17',
            name: 'Low mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 17,
            number: '18',
            name: 'Low mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 18,
            number: '19',
            name: 'Low mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 19,
            number: '20',
            name: 'Mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 20,
            number: '21',
            name: 'Mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 21,
            number: '22',
            name: 'Mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 22,
            number: '23',
            name: 'High mid band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 23,
            number: '24',
            name: 'High mid band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 24,
            number: '25',
            name: 'High mid band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 25,
            number: '26',
            name: 'High band threshold',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 26,
            number: '27',
            name: 'High band gain',
            type: 'double',
            precision: 1,
            minimum: -10,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 27,
            number: '28',
            name: 'High band threshold bypass',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 28,
            number: '29',
            name: 'Meters',
            type: 'select',
            options: [
                { id: 0, name: 'Band gain reduction' },
                { id: 1, name: 'Band level meters (peak)' },
                { id: 2, name: 'Automatic spectrum balance' },
            ],
        },
    ],
};
