// Exported
export default {
    id: 11,
    name: '3-Tap Delay',
    category: 'Delay',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Time',
            type: 'double',
            style: 'tap',
            precision: 0,
            minimum: 1,
            maximum: 3000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Gain base',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Pan base',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 3,
            number: '04',
            name: 'Feed',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'High cut',
            type: 'double',
            precision: 0,
            minimum: 200,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Factor A',
            type: 'select',
            options: [
                { id: 0, name: '1/4' },
                { id: 1, name: '3/8' },
                { id: 2, name: '1/2' },
                { id: 3, name: '2/3' },
                { id: 4, name: '1' },
                { id: 5, name: '4/3' },
                { id: 6, name: '3/2' },
                { id: 7, name: '2' },
                { id: 8, name: '3' },
            ],
        },
        {
            id: 7,
            number: '08',
            name: 'Gain A',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Pan A',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 9,
            number: '10',
            name: 'Factor B',
            type: 'select',
            options: [
                { id: 0, name: '1/4' },
                { id: 1, name: '3/8' },
                { id: 2, name: '1/2' },
                { id: 3, name: '2/3' },
                { id: 4, name: '1' },
                { id: 5, name: '4/3' },
                { id: 6, name: '3/2' },
                { id: 7, name: '2' },
                { id: 8, name: '3' },
            ],
        },
        {
            id: 10,
            number: '11',
            name: 'Gain B',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'Pan B',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 12,
            number: '13',
            name: 'Cross feedback',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 13,
            number: '14',
            name: 'Mono',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 14,
            number: '15',
            name: 'Dry',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
