// Exported
export default {
    id: 52,
    name: 'Stereo Imager',
    category: 'Enhancer',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Balance',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 1,
            number: '02',
            name: 'Mono pan',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 2,
            number: '03',
            name: 'Stereo pan',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 3,
            number: '04',
            name: 'Shelve gain',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Shelve frequency',
            type: 'double',
            precision: 0,
            minimum: 100,
            maximum: 1000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Shelve q',
            type: 'double',
            precision: 2,
            minimum: 1,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Output gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
