// Exported
export default {
    id: 44,
    name: 'Stereo Leisure Compressor',
    category: 'Compressor',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'Gain',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Peak reduction',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Compressor / limiter',
            type: 'boolean',
            style: 'toggle',
        },
        {
            id: 4,
            number: '05',
            name: 'Output gain',
            type: 'double',
            precision: 0,
            minimum: -18,
            maximum: 6,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
