// Exported
export default {
    id: 57,
    name: 'Dual Tube Stage',
    category: 'Amp simulation',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | Drive',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Even',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 50,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Odd',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 50,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'A | Low cut',
            type: 'double',
            precision: 0,
            minimum: 20,
            maximum: 200,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'A | High cut',
            type: 'double',
            precision: 0,
            minimum: 4000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'A | Bass gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'A | Bass frequency',
            type: 'double',
            precision: 0,
            minimum: 50,
            maximum: 400,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'A | Treble gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'A | Treble frequency',
            type: 'double',
            precision: 0,
            minimum: 1000,
            maximum: 10000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'B | Drive',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'B | Even',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 50,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 12,
            number: '13',
            name: 'B | Odd',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 50,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 13,
            number: '14',
            name: 'B | Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 14,
            number: '15',
            name: 'B | Low cut',
            type: 'double',
            precision: 0,
            minimum: 20,
            maximum: 200,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 15,
            number: '16',
            name: 'B | High cut',
            type: 'double',
            precision: 0,
            minimum: 4000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 16,
            number: '17',
            name: 'B | Bass gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 17,
            number: '18',
            name: 'B | Bass frequency',
            type: 'double',
            precision: 0,
            minimum: 50,
            maximum: 400,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 18,
            number: '19',
            name: 'B | Treble gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 19,
            number: '20',
            name: 'B | Treble frequency',
            type: 'double',
            precision: 0,
            minimum: 1000,
            maximum: 10000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
    ],
};
