// Exported
export default {
    id: 1,
    name: 'Ambience',
    category: 'Reverb',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Pre delay',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 200,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Decay',
            type: 'double',
            precision: 2,
            minimum: 0,
            maximum: 7.3,
            unit: 's',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Size',
            type: 'double',
            precision: 0,
            minimum: 2,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Damp',
            type: 'double',
            precision: 0,
            minimum: 1000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Diffuse',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 30,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Level',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'High cut',
            type: 'double',
            precision: 0,
            minimum: 200,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Mod',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },

        {
            id: 9,
            number: '10',
            name: 'Tail gain',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
