// Exported
export default {
    id: 58,
    name: 'Stereo Tube Stage',
    category: 'Amp simulation',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Drive',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Even',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 50,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Odd',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 50,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 20,
            maximum: 200,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'High cut',
            type: 'double',
            precision: 0,
            minimum: 4000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Bass gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'Bass frequency',
            type: 'double',
            precision: 0,
            minimum: 50,
            maximum: 400,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Treble gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'Treble frequency',
            type: 'double',
            precision: 0,
            minimum: 1000,
            maximum: 10000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
    ],
};
