// Exported
export default {
    id: 20,
    name: 'Suboctaver',
    category: 'Pitch',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '03',
            name: 'Direct',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '04',
            name: 'Octave 1',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '05',
            name: 'Octave 2',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '06',
            name: 'A',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 5,
            number: '08',
            name: 'Direct',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '09',
            name: 'Octave 1',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '10',
            name: 'Octave 2',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
