// Exported
export default {
    id: 47,
    name: 'Dual Ultimo Compressor',
    category: 'Compressor',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Input',
            type: 'double',
            precision: 0,
            minimum: -48,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Output',
            type: 'double',
            precision: 0,
            minimum: -48,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Attack',
            type: 'double',
            precision: 1,
            minimum: 1,
            maximum: 7,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'A | Release',
            type: 'double',
            precision: 1,
            minimum: 1,
            maximum: 7,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'A | Ratio',
            type: 'select',
            options: [
                { id: 0, name: '4' },
                { id: 1, name: '8' },
                { id: 2, name: '12' },
                { id: 3, name: '20' },
                { id: 4, name: 'Limit' },
            ],
        },
        {
            id: 6,
            number: '07',
            name: 'B | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 7,
            number: '08',
            name: 'B | Input',
            type: 'double',
            precision: 0,
            minimum: -48,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'B | Output',
            type: 'double',
            precision: 0,
            minimum: -48,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'B | Attack',
            type: 'double',
            precision: 1,
            minimum: 1,
            maximum: 7,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'B | Release',
            type: 'double',
            precision: 1,
            minimum: 1,
            maximum: 7,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'B | Ratio',
            type: 'select',
            options: [
                { id: 0, name: '4' },
                { id: 1, name: '8' },
                { id: 2, name: '12' },
                { id: 3, name: '20' },
                { id: 4, name: 'Limit' },
            ],
        },
    ],
};
