// Exported
export default {
    id: 38,
    name: 'Precision Limiter',
    category: 'Compressor',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Input gain',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 18,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Output gain',
            type: 'double',
            precision: 1,
            minimum: -18,
            maximum: 0,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Squeeze',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Knee',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 10,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Attack',
            type: 'double',
            precision: 2,
            minimum: 0.05,
            maximum: 1,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Release',
            type: 'double',
            precision: 0,
            minimum: 20,
            maximum: 2000,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'Stereo link',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 7,
            number: '08',
            name: 'Auto gain',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
