// Exported
export default {
    id: 54,
    name: 'Sound Maxer',
    category: 'Enhancer',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Low contour',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | Process',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'B | On',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 5,
            number: '06',
            name: 'B | Low contour',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'B | Process',
            type: 'double',
            precision: 1,
            minimum: 0,
            maximum: 10,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'B | Gain',
            type: 'double',
            precision: 1,
            minimum: -12,
            maximum: 12,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
