// Exported
export default {
    id: 22,
    name: 'Chorus + Chamber',
    category: 'Reverb',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'Speed',
            type: 'double',
            style: 'tap',
            precision: 2,
            minimum: 0.05,
            maximum: 4,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'Depth',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'Delay',
            type: 'double',
            precision: 1,
            minimum: 0.5,
            maximum: 50,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'Phase',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 180,
            unit: '°',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'Wave',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'Balance',
            type: 'double',
            precision: 0,
            minimum: -100,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
        {
            id: 6,
            number: '07',
            name: 'Pre delay',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 200,
            unit: 'ms',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'Decay',
            type: 'double',
            precision: 2,
            minimum: 0.1,
            maximum: 5,
            unit: 's',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'Size',
            type: 'double',
            precision: 0,
            minimum: 2,
            maximum: 100,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'Damp',
            type: 'double',
            precision: 0,
            minimum: 1000,
            maximum: 20000,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'Low cut',
            type: 'double',
            precision: 0,
            minimum: 10,
            maximum: 500,
            unit: 'Hz',
            scale: 'log',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'Mix',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
            component: 'knob',
        },
    ],
};
