// Exported
export default {
    id: 32,
    name: 'Stereo DeEsser',
    category: 'De esser',
    parameters: [
        {
            id: 0,
            number: '06',
            name: 'Mid/Side process',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '01',
            name: 'Mid or stereo low band reduction',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '02',
            name: 'Mid or stereo high band reduction',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '03',
            name: 'Side low band reduction',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '04',
            name: 'Side high band reduction',
            type: 'double',
            precision: 0,
            minimum: 1,
            maximum: 50,
            unit: '',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '05',
            name: 'Male',
            type: 'boolean',
            style: 'onOff',
        },
    ],
};
